version: '3'
services:
  python-with-prom-metrics:
    image: python-with-prom-metrics:latest
    ports:
      - "5000:5000"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - .\prometheus\prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: '123456'
    volumes:
      - .\grafana\provisioning:/etc/grafana/provisioning
      - .\grafana\dashboards:/etc/grafana/dashboards
      - .\grafana\provisioning\dashboards\dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - .\grafana\provisioning\datasources\datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
